<?php
/**
 * Patami IPS Framework
 *
 * @package IPSPATAMI
 * @version 3.4
 * @link https://bitbucket.org/patami/ipspatami
 *
 * @author Florian Wiethoff <florian.wiethoff@patami.com>
 * @copyright 2017 Florian Wiethoff
 *
 * @license GPL
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later
 * version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * By intentionally submitting any modifications, corrections or derivatives to this work, or any other work intended
 * for use with this Software, to the author, you confirm that you are the copyright holder for those contributions and
 * you grant the author a nonexclusive, worldwide, irrevocable, royalty-free, perpetual, license to use, copy, create
 * derivative works based on those contributions, and sublicense and distribute those contributions and any derivatives
 * thereof.
 */


namespace Patami\IPS\Services\Alexa\Skills\Custom\Intents;


use Patami\IPS\I18N\Translator;
use Patami\IPS\Services\Alexa\Skills\Custom\Exceptions\IntentNotFoundException;
use Patami\IPS\Services\Alexa\Skills\Custom\Exceptions\RedirectLoopException;
use Patami\IPS\Services\Alexa\Skills\Custom\ModuleIntent;
use Patami\IPS\Services\Alexa\Skills\Custom\Request;
use Patami\IPS\Services\Alexa\Skills\Custom\Intents\Exceptions\RedirectIntentNotSetException;
use Patami\IPS\Services\Alexa\Skills\Custom\Response;


/**
 * Intent class which redirects requests to another intent.
 * @package IPSPATAMI
 */
class RedirectIntent extends ModuleIntent
{

    protected function GetType()
    {
        return 'RedirectIntent';
    }

    /**
     * Returns the configuration properties of the intent.
     * The user can configure the intent name to which the request should be redirected.
     * @return array Configuration properties.
     */
    public function GetConfigurationProperties()
    {
        // Get the list of properties from the parent method
        $properties = parent::GetConfigurationProperties();

        // Push our properties to the list
        array_push($properties,
            array(
                'type' => self::PROPERTY_STRING,
                'name' => 'TargetIntentName',
                'default' => $this->GetDefaultTargetIntentNameProperty()
            )
        );

        // Return the property list
        return $properties;
    }

    /**
     * Returns the default intent name to which the request should be redirected.
     * @return string Intent name.
     */
    protected function GetDefaultTargetIntentNameProperty()
    {
        return '';
    }

    /**
     * Returns the configuration form of the intent.
     * The user can configure the intent name to which the request should be redirected.
     * @return array Configuration form.
     */
    public function GetConfigurationFormData()
    {
        // Get the parent form data
        $data = parent::GetConfigurationFormData();

        // Add nothing if the intent is not enabled
        if (! $this->IsEnabled()) {
            return $data;
        }

        // Push the target intent name form field if it is visible
        if ($this->IsTargetIntentNamePropertyVisible()) {
            array_push($data['elements'],
                array(
                    'type' => 'Label',
                    'label' => Translator::Get('patami.framework.services.alexa.custom.intents.redirectintent.form.target_intent_name.label')
                ),
                array(
                    'type' => 'ValidationTextBox',
                    'name' => 'TargetIntentName',
                    'caption' => ''
                )
            );
        }

        // Return the form data
        return $data;
    }

    /**
     * Checks if the intent name configuration field should be visible on the configuration page of the I/O module.
     * @return bool True if the configuration field should be visible.
     */
    protected function IsTargetIntentNamePropertyVisible()
    {
        return true;
    }

    /**
     * Processes the Alexa Custom Skill Intent request by redirecting to another intent.
     * This method is automatically called by the Execute() method.
     * @param Request $request Request object of the incoming request.
     * @return Response Response object to be sent back to the Amazon servers generated by the target intent.
     * @throws RedirectIntentNotSetException if the intent name is not set.
     * @throws IntentNotFoundException if no matching intent could be found either configured as IPS intent instance or
     * configured as a built-in intent class.
     * @throws RedirectLoopException if a loop was detected while processing a chain of redirects.
     */
    protected function DoExecute(Request $request)
    {
        // Get the target intent name
        $intentName = $this->ReadPropertyString('TargetIntentName');

        // Throw an exception if the intent name is not set
        if ($intentName == '') {
            throw new RedirectIntentNotSetException();
        }

        // Redirect the request and return the result
        return $request->RedirectToIntent($intentName);
    }

}