<?php
/**
 * Patami IPS Framework
 *
 * @package IPSPATAMI
 * @version 3.4
 * @link https://bitbucket.org/patami/ipspatami
 *
 * @author Florian Wiethoff <florian.wiethoff@patami.com>
 * @copyright 2017 Florian Wiethoff
 *
 * @license GPL
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later
 * version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * By intentionally submitting any modifications, corrections or derivatives to this work, or any other work intended
 * for use with this Software, to the author, you confirm that you are the copyright holder for those contributions and
 * you grant the author a nonexclusive, worldwide, irrevocable, royalty-free, perpetual, license to use, copy, create
 * derivative works based on those contributions, and sublicense and distribute those contributions and any derivatives
 * thereof.
 */


namespace Patami\IPS\Services\Alexa\Skills\Custom\Intents;


use Patami\IPS\Services\Alexa\Skills\Custom\Exceptions\CallbackIntentNotSetException;
use Patami\IPS\Services\Alexa\Skills\Custom\Exceptions\IntentNotFoundException;
use Patami\IPS\Services\Alexa\Skills\Custom\Exceptions\RedirectLoopException;
use Patami\IPS\Services\Alexa\Skills\Custom\ModuleIntent;
use Patami\IPS\Services\Alexa\Skills\Custom\Request;
use Patami\IPS\Services\Alexa\Skills\Custom\Response;


/**
 * Intent class which redirects requests to the callback intent from the user's active Alexa session.
 * @package IPSPATAMI
 */
class RedirectToCallbackIntent extends ModuleIntent
{

    protected function GetType()
    {
        return 'RedirectToCallbackIntent';
    }

    /**
     * Processes the Alexa Custom Skill Intent request by redirecting to the callback intent.
     * This method is automatically called by the Execute() method.
     * @param Request $request Request object of the incoming request.
     * @return Response Response object to be sent back to the Amazon servers generated by the callback intent.
     * @throws CallbackIntentNotSetException if no callback intent name is set in the session.
     * @throws IntentNotFoundException if no matching intent could be found either configured as IPS intent instance or
     * configured as a built-in intent class.
     * @throws RedirectLoopException if a loop was detected while processing a chain of redirects.
     */
    protected function DoExecute(Request $request)
    {
        // Redirect the request and return the result
        return $request->RedirectToCallbackIntent();
    }

}