<?php
/**
 * Patami IPS Framework
 *
 * @package IPSPATAMI
 * @version 3.4
 * @link https://bitbucket.org/patami/ipspatami
 *
 * @author Florian Wiethoff <florian.wiethoff@patami.com>
 * @copyright 2017 Florian Wiethoff
 *
 * @license GPL
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later
 * version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * By intentionally submitting any modifications, corrections or derivatives to this work, or any other work intended
 * for use with this Software, to the author, you confirm that you are the copyright holder for those contributions and
 * you grant the author a nonexclusive, worldwide, irrevocable, royalty-free, perpetual, license to use, copy, create
 * derivative works based on those contributions, and sublicense and distribute those contributions and any derivatives
 * thereof.
 */


namespace Patami\IPS\Services\Alexa\Skills\Custom\Intents;


use Patami\IPS\I18N\Translator;
use Patami\IPS\Services\Alexa\Skills\Custom\Intents\Exceptions\ActionScriptNotLoadedException;
use Patami\IPS\Services\Alexa\Skills\Custom\Intents\Exceptions\ActionScriptNotFoundException;
use Patami\IPS\Services\Alexa\Skills\Custom\Intents\Exceptions\ActionScriptNotSetException;
use Patami\IPS\Services\Alexa\Skills\Custom\Intents\Exceptions\InvalidActionScriptException;
use Patami\IPS\Services\Alexa\Skills\Custom\ModuleIntent;
use Patami\IPS\Services\Alexa\Skills\Custom\Request;
use Patami\IPS\Services\Alexa\Skills\Custom\Response;
use Patami\IPS\System\IPS;


/**
 * Intent class which executes an IPS script to process the Alexa request.
 * @package IPSPATAMI
 */
class ScriptIntent extends ModuleIntent
{

    protected function GetType()
    {
        return 'ScriptIntent';
    }

    /**
     * Returns the configuration properties of the intent.
     * The user can configure the IPS script which is executed to process the request.
     * @return array Configuration properties.
     */
    public function GetConfigurationProperties()
    {
        // Get the list of properties from the parent method
        $properties = parent::GetConfigurationProperties();

        // Push our properties to the list
        array_push($properties,
            array(
                'type' => self::PROPERTY_INTEGER,
                'name' => 'ScriptID',
                'default' => $this->GetDefaultScriptIdProperty()
            )
        );

        // Return the property list
        return $properties;
    }

    /**
     * Returns the default IPS object ID of the action script.
     * @return int IPS object ID of the action script.
     */
    protected function GetDefaultScriptIdProperty()
    {
        return 0;
    }

    /**
     * Returns the configuration form of the intent.
     * The user can configure the IPS script which is executed to process the request.
     * @return array Configuration form.
     */
    public function GetConfigurationFormData()
    {
        // Get the parent form data
        $data = parent::GetConfigurationFormData();

        // Add nothing if the intent is not enabled
        if (! $this->IsEnabled()) {
            return $data;
        }

        // Push the script select form field if it is visible
        if ($this->IsScriptIdPropertyVisible()) {
            array_push($data['elements'],
                array(
                    'type' => 'Label',
                    'label' => Translator::Get('patami.framework.services.alexa.custom.intents.scriptintent.form.script_id.label')
                ),
                array(
                    'type' => 'SelectScript',
                    'name' => 'ScriptID',
                    'caption' => ''
                )
            );
        }

        // Return the form data
        return $data;
    }

    /**
     * Checks if the action script configuration field should be displayed on the configuration form of the I/O module.
     * @return bool True if the configuration field should be displayed.
     */
    protected function IsScriptIdPropertyVisible()
    {
        return true;
    }

    /**
     * Processes the Alexa Custom Skill Intent request by executing a custom IPS action script.
     * This method is automatically called by the Execute() method.
     * @param Request $request Request object of the incoming request.
     * @return Response Response object to be sent back to the Amazon servers generated by the action script.
     * @throws ActionScriptNotSetException if the action script is not set.
     * @throws ActionScriptNotFoundException if the action script could not be found.
     * @throws ActionScriptNotLoadedException if the action script could not be loaded.
     * @throws InvalidActionScriptException if the action script could not be parsed or if there is no Execute()
     * function defined in the script or if a PHP error occurs while evaluating the script.
     */
    protected function DoExecute(Request $request)
    {
        // Get the script ID
        $scriptId = $this->ReadPropertyInteger('ScriptID');
        $this->Debug('Execute Script', $scriptId);

        // Throw an exception if the script is not set
        if (! $scriptId) {
            throw new ActionScriptNotSetException();
        }

        // Throw an exception if the script cannot be found
        if (! IPS::ScriptExists($scriptId)) {
            throw new ActionScriptNotFoundException();
        }

        // Load the script contents
        $script = IPS::GetScriptContent($scriptId);

        // Throw an exception if the script cannot be loaded
        if (! $script) {
            throw new ActionScriptNotLoadedException();
        }

        // Get the new function name
        $funcName = str_replace('\\', '_', get_called_class()) . '_Execute';

        // Rename the function in the script and add use statements
        $script = str_replace(
            'function Execute(',
            "use \\Patami\\IPS\\Services\\Alexa\\Skills\\Custom\\Request;\n" .
            "use \\Patami\\IPS\\Services\\Alexa\\Skills\\Custom\\Response;\n" .
            "use \\Patami\\IPS\\Services\\Alexa\\Skills\\Custom\\AskResponse;\n" .
            "use \\Patami\\IPS\\Services\\Alexa\\Skills\\Custom\\TellResponse;\n\n" .
            "function ${funcName}(",
            $script
        );

        // Capture error messages
        ob_start();

        // Evaluate the script
        $result = eval('?>' . $script);

        // Log errors, if any
        $errors = ob_get_contents();
        ob_end_clean();
        if ($errors != '') {
            $this->Debug('Script Parse Error', $errors);
            throw new InvalidActionScriptException();
        }

        // Throw an exception if script could not be parsed or the function was not defined in the script
        if ($result === false || ! function_exists($funcName)) {
            throw new InvalidActionScriptException();
        }

        // Capture error messages
        ob_start();

        // Execute the script function
        try {
            $this->Debug('Execute Function Start', $funcName);
            $response = $funcName($request);
        } finally {
            $this->Debug('Execute Function End', $funcName);

            // Log errors, if any
            $errors = ob_get_contents();
            ob_end_clean();
            if ($errors != '') {
                $this->Debug('Script Execute Error', $errors);
                throw new InvalidActionScriptException();
            }
        }

        // Return the script's response
        return $response;
    }

}