<?php
/**
 * Patami IPS Framework
 *
 * @package IPSPATAMI
 * @version 3.4
 * @link https://bitbucket.org/patami/ipspatami
 *
 * @author Florian Wiethoff <florian.wiethoff@patami.com>
 * @copyright 2017 Florian Wiethoff
 *
 * @license GPL
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later
 * version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * By intentionally submitting any modifications, corrections or derivatives to this work, or any other work intended
 * for use with this Software, to the author, you confirm that you are the copyright holder for those contributions and
 * you grant the author a nonexclusive, worldwide, irrevocable, royalty-free, perpetual, license to use, copy, create
 * derivative works based on those contributions, and sublicense and distribute those contributions and any derivatives
 * thereof.
 */


namespace Patami\IPS\Services\Alexa\Skills\Custom;


use Patami\IPS\System\Logging\DebugInterface;
use Patami\IPS\Services\Alexa\Skills\Custom\Exceptions\IntentNotEnabledException;


/**
 * Abstract base class for Amazon Alexa Custom Skill Intents.
 * @package IPSPATAMI
 */
abstract class Intent implements IntentInterface, DebugInterface
{

    /** @var IntentContainerInterface WebHook or WebOAuth I/O module object which displays the intent configuration form. */
    protected $container;

    /** @var DebugInterface Module object which receives debug messages generated by the intent. */
    protected $debugTarget;

    /**
     * Intent constructor.
     * @param IntentContainerInterface $container WebHook or WebOAuth I/O module object which uses the intent
     * configuration form.
     */
    public function __construct(IntentContainerInterface $container)
    {
        // Remember the container object
        $this->container = $container;

        // Remember the debug target object
        $this->debugTarget = $container;
    }

    /**
     * Static factory method that creates an new instance of the intent class.
     * @param IntentContainerInterface $container WebHook or WebOAuth I/O module object which uses the intent
     * configuration form.
     * @return $this New intent instance.
     */
    public static function Create(IntentContainerInterface $container)
    {
        // Return a new instance of this class
        $className = get_called_class();
        return new $className($container);
    }

    /**
     * Returns the intent name.
     * This method returns the name of the class (by stripping off the namespace from the FQCN).
     * It can be overridden to return an intent name different from the class name.
     * @return bool string Intent name.
     */
    public function GetName()
    {
        // Get the name of the called class
        $className = get_called_class();

        // Strip the namespace part if necessary
        if ($pos = strrpos($className, '\\')) {
            // Return the plain class name
            return substr($className, $pos + 1);
        }

        // Plain class name, return it
        return $pos;
    }

    /**
     * Checks if the intent is enabled.
     * Disabled intents will be ignored when searching for intents when a request comes in from the Amazon servers.
     * @return bool True if the intent is enabled.
     */
    public function IsEnabled()
    {
        return true;
    }

    /**
     * Returns the intent type.
     * This needs to be overridden by concrete child classes.
     * @return string Type of the intent.
     */
    abstract protected function GetType();

    /**
     * Processes the Alexa Custom Skill Intent request.
     * This method is automatically called by the Request class. It is only a wrapper method that calls the DoExecute()
     * method of the concrete child class to perform the actual processing on the request.
     * @param Request $request Request object of the incoming request.
     * @return Response Response object to be sent back to the Amazon servers.
     * @throws IntentNotEnabledException if the intent is disabled.
     * @internal
     * @see Intent::DoExecute()
     */
    public function Execute(Request $request)
    {
        // Send all debug to the request IO
        $this->debugTarget = $request->GetIO();

        $this->Debug('Executing Intent', sprintf('%s (%s)', $this->GetName(), get_called_class()));
        $this->Debug('Intent Type', $this->GetType());

        // Throw an exception if the intent is not enabled
        if (! $this->IsEnabled()) {
            $this->debugTarget = $this->container;
            throw new IntentNotEnabledException();
        }

        // Execute the intent
        try {
            $this->Debug('Intent Execution Start', $this->GetName());
            $response = $this->DoExecute($request);
        } finally {
            $this->Debug('Intent Execution End', $this->GetName());
            $this->debugTarget = $this->container;
        }

        // Set the request object for session handling
        if ($response instanceof Response) {
            /** @noinspection PhpInternalEntityUsedInspection */
            $response->SetRequest($request);
        }

        // Return the response
        return $response;
    }

    /**
     * Processes the Alexa Custom Skill Intent request.
     * This method is automatically called by the Execute() method.
     * It needs to be overridden by the concrete child class implementation.
     * @param Request $request Request object of the incoming request.
     * @return Response Response object to be sent back to the Amazon servers.
     */
    abstract protected function DoExecute(Request $request);

    public function Debug($tag, $message, array $data = null)
    {
        // Forward debugging to the debug target
        $this->debugTarget->Debug($tag, $message, $data);

        // Enable fluent interface
        return $this;
    }

}